import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {SearchIcon, MicrophoneIcon} from '@heroicons/react/solid';
import Header from '../components/Header'
import Footer from '../components/Footer';
import { useRef } from 'react';
import { useRouter } from 'next/router';

type SearchInputType = any;

const Home: NextPage = () => {
  const router = useRouter();
  const searchInputRef = useRef<SearchInputType | null>(null);

  // Todo: Imprement search function
  const search = (event: any) => {
    event.preventDefault();
    const term  = searchInputRef.current?.value;
    if (!term.trim()) return;
    router.push(`/search?term=${term.trim()}&searchType=`);
  }

  // Todo: Imprement randomSearch function
  const randomSearch = () => {
    console.log('randomSearch実行');
  }

  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header/>

      {/* Body */}
      <form className="flex flex-col items-center mt-40">
        <Image
        width="300"
        objectFit="cover"
        height="100"
        src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png"
        />
        <div className="flex w-full mt-5 mx-auto max-w-[90%] border border-gray-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 text-gray-500 mr-3"/>
          <input
            ref={searchInputRef}
            type="text"
            className="flex-grow focus:outline-none"
          />
          <MicrophoneIcon className="h-5"/>
        </div>
        <div className="flex flex-col sm:flex-row w-[50%] space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center">
          <button onClick={search} className="btn">
            Google Search
          </button>
          <button onClick={randomSearch} className="btn">
            I am feeling lucky
          </button>
        </div>
      </form>

      {/* Footer */}

      <Footer/>
    </div>
  )
}

export default Home
